name: Build and Deploy

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{ secrets.BUCKET }}
      REGION: ${{ secrets.REGION }}
      DISTRIBUTION_ID: ${{ secrets.DISTRIBUTION_ID }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          # @todo this is a typo in the github actions secret, I misstyped ACCESS. fix it later
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Copy files to production website
        run: |
          aws s3 sync . s3://${{env.BUCKET}} --delete --exclude ".git/*" --exclude ".github/*" --exclude "README.md"
      
      -name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.DISTRIBUTION_ID }} \
            --paths "/*"