name: Build and Deploy

on:
  push:
    branches: [master]

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      BUCKET: ${{ secrets.BUCKET }}
      REGION: ${{ secrets.REGION }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.REGION }}

      - name: Copy files to production website
        run: |
          aws s3 sync . s3://${{env.BUCKET}} --delete --exclude ".git/*" --exclude ".github/*" --exclude "README.md"